[Feat] 시간여행 가상공간 이미지 post api 구현
TeamDearToday/Deartoday-Server pull request #31
Opened 2022-07-14 18:09 UTC by heerucan

## 🚅 PR 한 줄 요약

시간여행 가상공간 이미지 post api 구현

## 💻 PR 세부 내용

- multer를 사용해서 s3 버킷에 이미지 파일 업로드 완..

2022-07-14 18:12 UTC, meenyweeny reviewed
..컨플릭트?

2022-07-15 00:39 UTC, shb03323 commented on src/controllers/timeTravel/TimeTravelController.ts
> + *  @route POST /image
이전 버전으로 바꾸어야 할 듯 합니다.

2022-07-15 00:40 UTC, shb03323 commented on src/interfaces/timeTravel/TimeTravelCreateDto.ts
> +  userId: string;
string 보다 mongoose.Types.ObjectId 로 하는 것이 더 괜찮아보입니다. string으로 했을 때 에러 안났었어?

2022-07-15 00:41 UTC, shb03323 commented on src/interfaces/user/UserInfo.ts
> +  id: mongoose.Types.ObjectId;
id를 추가한 이유가 있을까요?

2022-07-15 00:45 UTC, shb03323 requested changes
남긴 리뷰들 확인 부탁드립니다.

2022-07-15 09:15 UTC, heerucan commented on src/interfaces/timeTravel/TimeTravelCreateDto.ts
> +  userId: string;
넹 그치만 고치겟숨다

2022-07-15 09:18 UTC, heerucan commented on src/interfaces/user/UserInfo.ts
> +  id: mongoose.Types.ObjectId;
user를 어떻게 식별하지 했는데,,, accessToken으로 가능할 거 같아서 지우겟숨다

2022-07-15 09:20 UTC, merged